service: aws-daily-usage-notifier

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  timeout: 300
  environment:
    TOPIC_ARN: ${self:custom.SnsArn}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
            - ce:GetCostAndUsage
          Resource: '*'

resources:
  Resources:
    SnsTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: "AWS Daily Cost Usage"
        TopicName: "Cost-Notifier-Topic"
        Subscription:
          - Endpoint: ${self:custom.targetEmail}
            Protocol: email

functions:
  CostNotifier:
    handler: src/handler.costNotifier
    events:
      - schedule: cron(0 6 * * ? *)

custom:
  targetEmail: 'akbarrmdhn94@gmail.com'
  SnsTopic: !GetAtt  SnsTopic.TopicName
  SnsArn: !Ref SnsTopic